---
- name: Install openssh-server
  dnf:
    name: openssh-server
    state: present

- name: Configure sshd
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Restart sshd

- name: Enable sshd
  service:
    name: sshd
    state: started
    enabled: true
