---
- name: Add hostname to hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop_control:
    label: "{{ item.label }}"
  loop:
    - label: "IPv4 {{ hostname }}"
      regexp: "^127\\.0\\.0\\.1.*# ansible hostname$"
      line: "127.0.0.1    {{ hostname }} # ansible hostname"
    - label: "IPv6 {{ hostname }}"
      regexp: "^::1.*# ansible hostname$"
      line: "::1    {{ hostname }} # ansible hostname"

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Install base packages
  yum:
    name: "{{ base_packages }}"
    state: present

- name: Enable watchdog timer
  lineinfile:
    path: /etc/systemd/system.conf
    regex: "^#?RuntimeWatchdogSec"
    line: "RuntimeWatchdogSec=30"
  notify: Reload systemctl daemon
